apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: wordpress
    tier: nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-config-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-log-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - name: nginx-persistent-config-storage
          mountPath: /etc/nginx
        - name: nginx-persistent-log-storage
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-persistent-config-storage
        persistentVolumeClaim:
          claimName: nginx-pv-config-claim
      - name: nginx-persistent-log-storage
        persistentVolumeClaim:
          claimName: nginx-pv-log-claim
