apiVersion: v1
kind: Pod
metadata:
  name: fedora-2
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  containers:
  - command:
    - sleep
    - infinity
    image: fedora
    name: fedora
