apiVersion: v1
kind: Pod
metadata:
  name: fedora-1
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  containers:
  - command:
    - sleep
    - infinity
    image: fedora
    name: fedora
