apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: home-directory
          hostPath:
            path: /home/mwoodpatrick
            type: Directory
        - name: project-directory
          hostPath:
            path: /projects
            type: Directory
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
         - name: home-directory
           mountPath: /home/mwoodpatrick
         - name: project-directory
           mountPath: /projects
