apiVersion: v1
kind: Pod
metadata:
  name: my-hostpath-app
spec:
  containers:
  - name: my-hostpath-app
    image: nginx
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: my-shared-projects-volume
      mountPath: /projects
  volumes:
  - name: my-shared-projects-volume
    hostPath:
      path: /projects
