apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: arch
  name: arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arch
    spec:
      containers:
      - image: archlinux
        name: arch
        command: ["/bin/sleep", "3650d"]
        resources: {}

