apiVersion: v1
kind: Pod
metadata:
  name: longhorn-volume-test
  namespace: default
spec:
  containers:
  - name: longhorn-volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: longhorn-volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: longhorn-volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
